### ISSUE TITLE
Can the content be translated into other languages and provided?

### ISSUE THREAD

**Issue by kkame** [LaravelDaily/laravel-tips#9]
Thanks for providing good documentation.

I would like to provide this document translated into Korean.

Is this an acceptable behavior?

Is there any recommended method if possible?

**Comment by PovilasKorop** [comment]
@kkame you can fork this repository to your own and then do the translations there.

**Comment by edysarwo** [comment]
Dear There,
Is there something wrong? I do really apologized if i did something wrong.

Im new in all things about git and github.
How i can help you?

**Comment by trollfalgar** [comment]
Would be nice have support for other languages in one repository alone.

**Comment by PovilasKorop** [comment]
@trollfalgar maybe, but the current one-page Readme file is already pretty huge. How do you envision that second part, to be added at the bottom and make the page even longer? Or restructure the repository and create separate pages for each language?

**Comment by FaycalBorsali** [comment]
I like the idea of having multi-language tips. People do need that.
I believe OP was just asking for permission to use the content as there is no license for the repo.

The way I see it is
- we can PR the repo with a multi-language folder structure
- we could fork and translate but it would be nice to have links to all the translations (with disclaimers that you can't possibly check all the content by yourself)
- or everyone gives their tips by themselves independently 

Either way, the real questions are : 
- Do you (as repo owner) want that page to become like a small open source project that needs maintenance (I believe few hours a month would be enough) => we'd need contribution guidelines 
- And do you accept that people share your work (with your exact structure and the fruit of your efforts) in other languages?

I say 'we' because I was also thinking of maybe providing some translation.

**Comment by trollfalgar** [comment]
@PovilasKorop 
In fact the file is huge now, and it may be even more so if new tips were added. I suggest separate pages, people can contribute with pull requests with new files or corrections, updates to existing ones, etc.

**Comment by PovilasKorop** [comment]
@FaycalBorsali @trollfalgar well, I didn't have any long-term plans to make it a community repository, I was just planning to share my own tips. This means, that if people do provide translations to all tips, then if I add 10 more tips, then I need to find those people again for translations? Or leave them un-translated?

I guess the best way for me personally would be if you do create your own (forked or not) repositories in your languages. I give permission to do that, don't have much time to specify all official licensing stuff. And then you add a PR to my repository, adding the LINK to your repository in your language. Which will also be a boost to your own personal Github profile and not mine :)

What do you think?

**Comment by FaycalBorsali** [comment]
@PovilasKorop thank you !

I think the way you describe it is reasonable enough

**Comment by trollfalgar** [comment]
@PovilasKorop yep, totally valid. We can do that.

**Comment by kkame** [comment]
I will be translating in a separate repository as discussed above.
After completion, we will pull request the address.

If you plan to translate and manage various languages more systematically, I think it's a good idea to review gitlocalize.com.

However, I do not want to burden the maintainer through the use of these tools. Please review it as it is not burdensome.
